var triplett_dictionary={
    'UUU':['Phe', 'Phenylalanin'],
    'UUC':['Phe', 'Phenylalanin'],    
    'UUA':['Leu', 'Leucin'],    
    'UUG':['Leu', 'Leucin'],
    'CUU':['Leu', 'Leucin'],    
    'CUC':['Leu', 'Leucin'],    
    'CUA':['Leu', 'Leucin'],    
    'CUG':['Leu', 'Leucin'],
    'AUU':['Ile', 'Isoleucin'],      
    'AUC':['Ile', 'Isoleucin'],      
    'AUA':['Ile', 'Isoleucin'],      
    'AUG':['Met/Start', 'Methionin/Start'],
    'GUU':['Val', 'Valin'],    
    'GUC':['Val', 'Valin'],    
    'GUA':['Val', 'Valin'],    
    'GUG':['Val', 'Valin'],
    'UCU':['Ser', 'Serin'],    
    'UCC':['Ser', 'Serin'],    
    'UCA':['Ser', 'Serin'],    
    'UCG':['Ser', 'Serin'],
    'CCU':['Pro', 'Prolin'],    
    'CCC':['Pro', 'Prolin'],    
    'CCA':['Pro', 'Prolin'],    
    'CCG':['Pro', 'Prolin'],
    'ACU':['Thr', 'Threonin'],    
    'ACC':['Thr', 'Threonin'],    
    'ACA':['Thr', 'Threonin'],    
    'ACG':['Thr', 'Threonin'],
    'GCU':['Ala', 'Alanin'],    
    'GCC':['Ala', 'Alanin'],    
    'GCA':['Ala', 'Alanin'],    
    'GCG':['Ala', 'Alanin'],
    'UAU':['Tyr', 'Tyrosin'],    
    'UAC':['Tyr', 'Tyrosin'],    
    'UAA':['Stop', 'Stop'],    
    'UAG':['Stop', 'Stop'],
    'CAU':['His', 'Histidin'],    
    'CAC':['His', 'Histidin'],    
    'CAA':['Gln', 'Glutamin'],    
    'CAG':['Gln', 'Glutamin'],
    'AAU':['Asn', 'Asparagin'],      
    'AAC':['Asn', 'Asparagin'],      
    'AAA':['Lys', 'Lysin'],    
    'AAG':['Lys', 'Lysin'],
    'GAU':['Asp', 'Asparaginsäure'],   
    'GAC':['Asp', 'Asparaginsäure'],   
    'GAA':['Glu', 'Glutaminsäure'],    
    'GAG':['Glu', 'Glutaminsäure'],
    'UGU':['Cys', 'Cystein'],    
    'UGC':['Cys', 'Cystein'],    
    'UGA':['Stop', 'Stop'],    
    'UGG':['Trp', 'Tryptophan'],
    'CGU':['Arg', 'Arginin'],    
    'CGC':['Arg', 'Arginin'],    
    'CGA':['Arg', 'Arginin'],    
    'CGG':['Arg', 'Arginin'],
    'AGU':['Ser', 'Serin'],    
    'AGC':['Ser', 'Serin'],    
    'AGA':['Arg', 'Arginin'],    
    'AGG':['Arg', 'Arginin'],
    'GGU':['Gly', 'Glycin'],    
    'GGC':['Gly', 'Glycin'],    
    'GGA':['Gly', 'Glycin'],    
    'GGG':['Gly', 'Glycin']
}
     
var as_dictionary={
    'Ala':'A',     
    'Cys':'C', 
    'Asp':'D',    
    'Glu':'E',
    'Phe':'F',     
    'Gly':'G',  
    'His':'H',    
    'Ile':'I',
    'Lys':'K',     
    'Leu':'L',  
    'Met/Start':'M',    
    'Asn':'N',
    'Pro':'P',     
    'Gln':'Q',  
    'Arg':'R',    
    'Ser':'S',
    'Thr':'T',     
    'Val':'V',  
    'Trp':'W',    
    'Tyr':'Y',
    'Stop':'⚠' // auch U für Selenocystein möglich oder ⊘
}
     
