var texte={
'lichtreaktion':{
    'ort':'Thylakoidmembran (innere Chloroplastenmembran, entspricht der Chloroplasten-Zellmembran)',
    'ed':'Zwölf Wassermoleküle',
    'zwi':'Protonen, Sauerstoffradikale, freie Elektronen an einem Redox-Protein',
    'prod':'Sechs Moleküle elementarer Sauerstoff',
    'atp':'Bildung von 18 ATP Molekülen',
    'redaeq':'Bildung von 12 NADPH₂⁺ Molekülen',
    'exerg':'Keine, die endergonischen Reaktionen werden hier nur durch die Aufnahme von Lichtenergie angetrieben',
    'enderg':'Elektrolyse von Wasser; Bildung der Reduktionsäquivalente und von ATP',
    },
'calvinzyklus':{
    'ort':'Stroma (Chloroplasten-Zellplasma)',
    'ed':'Sechs Kohlenstoffidoxid-Moleküle',
    'zwi':'Glycerinsäure und Glycerinaldehyd, nach der Regeneration Ribulose als CO₂-Akzeptor',
    'prod':'Ein Glucose-Molekül und sechs Wassermoleküle',
    'atp':'Verbrauch von 18 ATP Molekülen',
    'redaeq':'Verbrauch von 12 NADPH₂⁺ Molekülen',
    'exerg':'Oxidation der Reduktionsäquivalente NADPH₂⁺ zu NADP⁺ und Hydrolyse von ATP zu ADP und Pi',
    'enderg':'Reduktion von Kohlenstoffdioxid (mittlere OZ[C]=+IV) zu Glucose (mittlere OZ[C]=0)',
    },
'glykolyse':{
    'ort':'Zellplasma',
    'ed':'Ein Glucose-Molekül und sechs Wassermoleküle',
    'zwi':'Mehrere Triosephosphate (Abkürzungen z.B. GAP, DHAP, 3-PG, 2-PG, PEP)',
    'prod':'Zwei Moleküle Brenztraubensäure (= Pyruvat)',
    'atp':'Gewinnung von 2 ATP Molekülen',
    'redaeq':'Gewinnung von 2 NADH₂⁺ Molekülen',
    'exerg':'Schrittweise Oxidation von Glucose zu Brenztraubensäure',
    'enderg':'Bildung der Reduktionsäquivalente und von ATP',
    },
'citratzyklus':{
    'ort':'Zunächst noch im Zellplasma Decarboxylierung, eigentlicher Kreisprozess in der Matrix (Mitochondrien-Zellplasma)',
    'ed':'Zwei Moleküle Brenztraubensäure (= Pyruvat)',
    'zwi':'Essigsäure (= Acetyl-CoA, Aktivierte Essigsäure) und Kohlenstoffdioxid; Zitronensäure (= Citrat), Oxalessigsäure (= Oxalacetat)',
    'prod':'Kohlenstoffdioxid',
    'atp':'Gewinnung von 2 ATP Molekülen',
    'redaeq':'Gewinnung von 8 NADH₂⁺ Molekülen und 2 FADH₂⁺ Molekülen',
    'exerg':'Schrittweise Oxidation von Brenztraubensäure zu Kohlenstoffdioxid',
    'enderg':'Bildung der Reduktionsäquivalente und von ATP',
    },
'endoxidation':{
    'ort':'Innere Mitochondrienmembran (entspricht der Mitochondrien-Zellmembran)',
    'ed':'Sechs Sauerstoffmoleküle',
    'zwi':'Sauerstoffradikale, freie Elektronen an einem Redox-Protein, Protonen',
    'prod':'Zwölf Wassermoleküle',
    'atp':'Bildung von 28 ATP Molekülen (10 • 2,5 ATP pro NADH₂⁺+ 2 • 1,5 ATP pro FADH₂⁺)',
    'redaeq':'Verbrauch von 10 NADH₂⁺ und 2 FADH₂⁺ Molekülen (vgl. Energiebilanzberechnung)',
    'exerg':'Reduktion von elementarem Sauerstoff zu Wasser; Oxidation der Reduktionsäquivalente NADH₂⁺ zu NAD⁺',
    'enderg':'Bildung von ATP',
    },
'decarboxylierung':{
    'ort':'Zellplasma',
    'ed':'Zwei Moleküle Brenztraubensäure',
    'zwi':'--',
    'prod':'Zwei Moleküle Ethanal (= Acetaldehyd) und zwei Kohlenstoffidoxid-Moleküle',
    'atp':'--',
    'redaeq':'--',
    'exerg':'--',
    'enderg':'--',
    },
'reduktionsschritt_alk':{
    'ort':'Zellplasma',
    'ed':'Zwei Moleküle Ethanal (= Acetaldehyd)',
    'zwi':'--',
    'prod':'Zwei Moleküle Ethanol',
    'atp':'--',
    'redaeq':'Verbrauch von 2 NADH₂⁺ Molekülen',
    'exerg':'--',
    'enderg':'--',
    },
'reduktionsschritt_milch':{
    'ort':'Zellplasma',
    'ed':'Zwei Moleküle Brenztraubensäure (= Pyruvat)',
    'zwi':'--',
    'prod':'Zwei Moleküle Milchsäure (= Lactat)',
    'atp':'--',
    'redaeq':'Verbrauch von 2 NADH₂⁺ Molekülen',
    'exerg':'--',
    'enderg':'--',
    }
}
